Dev/autocomplete customdescription
Woosmap/openapi-specification pull request #9
Opened 2022-02-10 08:22 UTC by cdartnell-wgs

adds custom_description parameter to localities autocomplete API

refs WebGeoServices/localities#305

2022-02-10 09:41 UTC, gaelsimon requested changes
You should also specify the new parameter in allowed parameters for the path /localities/autocomplete in this file:

`specification/paths/localities/localitiesAutocomplete.yml`


I assume the response Schema will also echo this field `custom_description` ?
`specification/schemas/LocalitiesAutocompleteResponse.yml`

2022-02-10 13:03 UTC, cdartnell-wgs commented
> 

this parameter will impact the shape of the description field in the response. No new parameter will be added.

2022-02-11 08:14 UTC, gaelsimon reviewed
Nice!

2022-02-11 08:15 UTC, gaelsimon approved these changes

2022-02-14 09:44 UTC, D4fnk approved these changes

2022-03-30 14:46 UTC, merged